FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
	openssh-server \
	python3 \
	sudo && \
	rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/.ssh
RUN chmod 700 /root/.ssh

COPY redis_cluster_key.pub /root/.ssh/authorized_keys

RUN chmod 600 /root/.ssh/authorized_keys

RUN mkdir -p /run/sshd

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
