[redis_nodes]
redis-node-1 ansible_host=127.0.0.1 ansible_port=3311 redis_cluster_ip=10.10.0.11
redis-node-2 ansible_host=127.0.0.1 ansible_port=3312 redis_cluster_ip=10.10.0.12
redis-node-3 ansible_host=127.0.0.1 ansible_port=3313 redis_cluster_ip=10.10.0.13
redis-node-4 ansible_host=127.0.0.1 ansible_port=3314 redis_cluster_ip=10.10.0.14
redis-node-5 ansible_host=127.0.0.1 ansible_port=3315 redis_cluster_ip=10.10.0.15
redis-node-6 ansible_host=127.0.0.1 ansible_port=3316 redis_cluster_ip=10.10.0.16

[redis_nodes:vars]
ansible_user=root
ansible_ssh_private_key_file=./infra/redis_cluster_key
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
ansible_remote_tmp=/root/.ansible/tmp